CREATE TABLE testtask (
  id INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
  student_id INT NOT NULL,
  class_id INT NOT NULL,
  contents VARCHAR(255) NOT NULL,
  deadline DATETIME NOT NULL,
  submitway VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)DEFAULT CHARSET = utf8;
